#####################################################################################################################################
# USD Asset Viewer | Core | Config
# Configure the core of the USD Asset Viewer.
#####################################################################################################################################
[settings]
use_hydra = false
usd_example_path = "core/asset/usd/example.usdc"

[glfw]
title = "USD Asset Viewer"
window_size = [1280, 720]
gl_color = [0.1, 0.2, 0.1, 1.0]

[config]
docking = false

[window]
ui_scale = 1.0

[window.flags]
no_move = true
no_resize = true
no_close = true
no_titlebar = true
no_docking = true
no_scrollbar = true


[window.style_color]
background_color = [0.3, 0.3, 0.3, 1.0]
border_color = [0.0, 0.0, 0.0, 1.0]

[window.style_var]
item_spacing = [5, 5]
item_padding = [5, 5]
border_size = 1.0













