#####################################################################################################################################
# USD Asset Viewer | Core | Config
# Configure the core of the USD Asset Viewer.
#####################################################################################################################################
[settings]
use_hydra = true
default_usd = "example_sphere.usdc"


[glfw]
title = "USD Asset Viewer"
window_size = [1280, 720]
gl_color = [0.1, 0.1, 0.1, 1.0]
vsync = true


[config]
docking = false


[window]
font_scale = 1.0


[window.flags]
no_move = true
no_resize = true
no_titlebar = true
no_docking = true
no_scrollbar = true
no_bring_to_front = true


[window.style_color]
text = [0.65, 0.65, 0.65, 1.0]
background = [0.2, 0.2, 0.2, 1.0]
border = [0.0, 0.0, 0.0, 1.0]


[window.style_var]
item_spacing = [5, 5]
window_padding = [5, 5]
border_size = 1.0
rounding = 6


[menu_bar.style_color]
menu_bar = [0.2, 0.2, 0.2, 1.0]


[menu_bar.style_var]
popup_border_size = 1.0
popup_rounding = 6


[title.style_color]
title = [0.3, 0.3, 0.3, 1.0]
title_active = [0.3, 0.3, 0.3, 1.0]


[header.style_color]
header = [0.3, 0.3, 0.3, 1.0]
header_hovered = [0.4, 0.4, 0.4, 1.0]
header_active = [0.5, 0.5, 0.5, 1.0]











