#####################################################################################################################################
# USD Asset Viewer | Core | Config
#####################################################################################################################################

[window]
window_size = [400, 800]
window_position = [0, 0]
ui_scale = 1.0


[window.flags]
no_move = true
no_resize = true
no_close = true
no_titlebar = true

[window.style_color]


[window.style_var]
line_height = 24
scale = 1.0
item_spacing = [8, 12]
padding = [5, 5]


[window.title]
title = "USD Asset Viewer"


[window.title.style_color]
bg_color = [0.1, 0.1, 0.1, 1.0]
bg_color_active = [0.2, 0.2, 0.2, 1.0]
bg_color_inactive = [0.1, 0.1, 0.1, 1.0]
bg_color_hovered = [0.3, 0.3, 0.3, 1.0]
bg_color_clicked = [0.4, 0.4, 0.4, 1.0]
bg_color_disabled = [0.5, 0.5, 0.5, 1.0]


[window.title.style_var]

rounding = 0.0











