#####################################################################################################################################
# USD Asset Viewer | Core | Config
#####################################################################################################################################
[settings]
default_usd = "example_sphere.usdc"
default_font = "arial.ttf"


[glfw]
title = "USD Asset Viewer"
window_size = [1280, 720]
gl_color = [0.1, 0.1, 0.1, 1.0]
vsync = true
msaa = 4

[config]
docking = false


[window]
font_scale = 1.0
font_size_tiny = 8.0
font_size_small = 12.0
font_size_medium = 18.0
font_size_large = 24.0


[window.flags]
no_background = true
no_move = true
no_resize = true
no_title_bar = true
no_docking = true
no_scrollbar = true
no_bring_to_front_on_focus = true


[window.style_color]
text = [0.65, 0.65, 0.65, 1.0]
window_bg = [0.2, 0.2, 0.2, 1.0]
border = [0.0, 0.0, 0.0, 1.0]


[window.style_var]
item_spacing = [5, 5]
window_padding = [10, 10]
window_border_size = 0.0
window_rounding = 0.0


[menu_bar.style_color]
menu_bar_bg = [0.2, 0.2, 0.2, 1.0]


[menu_bar.style_var]
popup_border_size = 1.0
popup_rounding = 6


[title.style_color]
title_bg = [0.3, 0.3, 0.3, 1.0]
title_bg_active = [0.3, 0.3, 0.3, 1.0]


[header.style_color]
header = [0.3, 0.3, 0.3, 1.0]
header_hovered = [0.4, 0.4, 0.4, 1.0]
header_active = [0.5, 0.5, 0.5, 1.0]


#####################################################################################################################################
# USD Asset Viewer | Tool | Outliner
#####################################################################################################################################

[outliner]
width = 350

[outliner.flags]
no_move = true
no_resize = true
no_title_bar = true
no_docking = true


[outliner.style_color]
window_bg = [0.15, 0.15, 0.15, 1.0]
border = [0.0, 0.0, 0.0, 1.0]
text = [0.65, 0.65, 0.65, 1.0]


[outliner.style_var]
item_spacing = [5, 5]
window_padding = [10, 10]
window_border_size = 1.0
window_rounding = 0.0

#####################################################################################################################################
# USD Asset Viewer | Tool | Trackbar
#####################################################################################################################################


[trackbar]
height = 40

[trackbar.flags]
no_move = true
no_resize = true
no_title_bar = true
no_docking = true


[trackbar.style_color]
window_bg = [0.15, 0.15, 0.15, 1.0]
border = [0.0, 0.0, 0.0, 1.0]
text = [0.65, 0.65, 0.65, 1.0]


[trackbar.style_var]
item_spacing = [5, 5]
window_padding = [10, 10]
window_border_size = 1.0
window_rounding = 0.0

#####################################################################################################################################
# USD Asset Viewer | Tool | Detail
#####################################################################################################################################


[detail]
width = 250


[detail.flags]
no_move = true
no_resize = true
no_title_bar = true
no_docking = true


[detail.style_color]
window_bg = [0.15, 0.15, 0.15, 1.0]
border = [0.0, 0.0, 0.0, 1.0]
text = [0.65, 0.65, 0.65, 1.0]


[detail.style_var]
item_spacing = [5, 5]
window_padding = [10, 10]
window_border_size = 1.0
window_rounding = 0.0


#####################################################################################################################################
# USD Asset Viewer | Tool | Viewport
#####################################################################################################################################


[viewport]
up_axis = "Z"
default_draw_style = "flat"
grid_color = [0.25, 0.25, 0.25, 1.0]
clipping_range = [1.0, 10000000.0]
focal_length = 35.0
grid_size = 1500
grid_density = 15

[viewport.flags]
no_move = true
no_resize = true
no_title_bar = true
no_docking = true
no_background = true
no_scrollbar = true


[viewport.style_color]
window_bg = [0.15, 0.15, 0.15, 1.0]
border = [0.0, 0.0, 0.0, 1.0]
text = [0.65, 0.65, 0.65, 1.0]


[viewport.style_var]
item_spacing = [5, 5]
window_padding = [10, 10]
window_border_size = 1.0
window_rounding = 0.0


[viewport.draw_style.wireframe]
name = "Wireframe"
icon = "WIREFRAME_ICON"
draw_mode = "DRAW_WIREFRAME"
enable_lighting = false

[viewport.draw_style.flat]
name = "Flat Shading"
icon = "FLAT_ICON"
draw_mode = "DRAW_WIREFRAME_ON_SURFACE"
enable_lighting = false

[viewport.draw_style.full]
name = "Full Shading"
icon = "FULL_ICON"
draw_mode = "DRAW_SHADED_SMOOTH"
enable_lighting = true




