#####################################################################################################################################
# USD Asset Viewer | Tool | Panel | Config
# Configure the core of the USD Asset Viewer.
#####################################################################################################################################


[outliner]
horizontal_range = 0.25
vertical_range = 0.95


[trackbar]
horizontal_range = 1.0
vertical_range = 0.05

[detail]
horizontal_range = 0.25
vertical_range = 0.95

[viewport]
horizontal_range = 0.50
vertical_range = 0.95
